/**
 * Lugares del mundo de La Rueda del Tiempo.
 * Coordenadas en píxeles de la imagen data/img/wot-map.jpg (3000 x 2250),
 * medidas desde la esquina superior izquierda: [x, y].
 * type: ciudad | pueblo | ruinas | region | montaña | bosque | isla | mar | lugar
 */
var WOT_PLACES = [
    // ── Grandes ciudades ─────────────────────────────────────────────
    { name: "Tar Valon",     alt: ["torre blanca", "white tower"], type: "ciudad", px: [2288, 852] },
    { name: "Caemlyn",       alt: [],                    type: "ciudad", px: [2138, 1336] },
    { name: "Cairhien",      alt: ["cairhien (ciudad)"], type: "ciudad", px: [2448, 1057] },
    { name: "Tear",          alt: ["piedra de tear"],    type: "ciudad", px: [2355, 1837] },
    { name: "Illian",        alt: [],                    type: "ciudad", px: [1968, 2066] },
    { name: "Ebou Dar",      alt: [],                    type: "ciudad", px: [1457, 1991] },
    { name: "Amador",        alt: ["amadicia (capital)"],type: "ciudad", px: [1234, 1712] },
    { name: "Tanchico",      alt: [],                    type: "ciudad", px: [757, 1511] },
    { name: "Falme",         alt: ["toman head"],        type: "ciudad", px: [654, 1223] },
    { name: "Bandar Eban",   alt: [],                    type: "ciudad", px: [777, 862] },
    { name: "Maradon",       alt: [],                    type: "ciudad", px: [1643, 461] },
    { name: "Chachin",       alt: [],                    type: "ciudad", px: [2039, 464] },
    { name: "Shol Arbela",   alt: [],                    type: "ciudad", px: [2328, 461] },
    { name: "Fal Dara",      alt: [],                    type: "ciudad", px: [2645, 434] },
    { name: "Fal Moran",     alt: [],                    type: "ciudad", px: [2622, 480] },
    { name: "Whitebridge",   alt: ["puente blanco"],     type: "ciudad", px: [1691, 1327] },
    { name: "Lugard",        alt: [],                    type: "ciudad", px: [1859, 1527] },
    { name: "Far Madding",   alt: [],                    type: "ciudad", px: [2178, 1586] },
    { name: "Mayene",        alt: [],                    type: "ciudad", px: [2860, 2006] },
    { name: "Godan",         alt: [],                    type: "ciudad", px: [2761, 1872] },
    { name: "Baerlon",       alt: [],                    type: "ciudad", px: [1360, 1182] },
    { name: "Jehannah",      alt: [],                    type: "ciudad", px: [1350, 1441] },
    { name: "Katar",         alt: [],                    type: "ciudad", px: [1162, 1051] },
    { name: "Elmora",        alt: [],                    type: "ciudad", px: [971, 1568] },
    { name: "Salidar",       alt: [],                    type: "ciudad", px: [1553, 1766] },

    // ── Pueblos y aldeas ─────────────────────────────────────────────
    { name: "Emond's Field", alt: ["campo de emond", "dos rios", "two rivers"], type: "pueblo", px: [1306, 1244] },
    { name: "Watch Hill",    alt: ["colina del vigia"],  type: "pueblo", px: [1304, 1226] },
    { name: "Deven's Ride",  alt: ["vado de deven"],     type: "pueblo", px: [1302, 1261] },
    { name: "Four Kings",    alt: ["cuatro reyes"],      type: "pueblo", px: [1988, 1328] },
    { name: "Aringill",      alt: [],                    type: "pueblo", px: [2302, 1340] },
    { name: "Maerone",       alt: [],                    type: "pueblo", px: [2311, 1323] },
    { name: "Market Sheran", alt: [],                    type: "pueblo", px: [2035, 1314] },
    { name: "Arien",         alt: [],                    type: "pueblo", px: [1904, 1334] },
    { name: "Kore Springs",  alt: [],                    type: "pueblo", px: [2045, 1231] },
    { name: "New Braem",     alt: [],                    type: "pueblo", px: [2155, 1230] },
    { name: "Jurene",        alt: [],                    type: "pueblo", px: [2298, 1220] },
    { name: "Remen",         alt: [],                    type: "pueblo", px: [1770, 1561] },
    { name: "So Habor",      alt: [],                    type: "pueblo", px: [1565, 1627] },
    { name: "Brytan",        alt: [],                    type: "pueblo", px: [1525, 1672] },
    { name: "Malden",        alt: [],                    type: "pueblo", px: [1602, 1799] },
    { name: "Alcruna",       alt: [],                    type: "pueblo", px: [993, 1380] },
    { name: "Denhuir",       alt: [],                    type: "pueblo", px: [2183, 820] },
    { name: "Tremonsien",    alt: [],                    type: "pueblo", px: [2530, 940] },
    { name: "Selean",        alt: [],                    type: "pueblo", px: [2727, 918] },
    { name: "Taien",         alt: [],                    type: "pueblo", px: [2823, 890] },
    { name: "Canluum",       alt: [],                    type: "pueblo", px: [2100, 520] },
    { name: "Manala",        alt: [],                    type: "pueblo", px: [2063, 500] },
    { name: "Ravinda",       alt: [],                    type: "pueblo", px: [2059, 484] },
    { name: "Medo",          alt: [],                    type: "pueblo", px: [2527, 498] },

    // ── Ruinas y lugares señalados ───────────────────────────────────
    { name: "Shadar Logoth", alt: ["aridhol"],           type: "ruinas", px: [1462, 1155] },
    { name: "Shayol Ghul",   alt: [],                    type: "montaña", px: [2395, 75] },
    { name: "Dragonmount",   alt: ["monte dragon", "monte del dragon"], type: "montaña", px: [2264, 900] },
    { name: "Tower of Ghenjei", alt: ["torre de ghenjei"], type: "lugar", px: [1583, 1165] },
    { name: "Tarwin's Gap",  alt: ["paso de tarwin"],    type: "lugar", px: [2684, 338] },
    { name: "Jangai Pass",   alt: ["paso jangai", "jengai pass"], type: "lugar", px: [2911, 893] },
    { name: "Niamh Passes",  alt: ["pasos de niamh"],    type: "lugar", px: [2925, 498] },
    { name: "Kinslayer's Dagger", alt: ["daga del asesino de parientes"], type: "montaña", px: [2639, 893] },
    { name: "World's End",   alt: ["fin del mundo"],     type: "lugar", px: [1309, 505] },
    { name: "Stedding Shangtai", alt: [],                type: "lugar", px: [2935, 1777] },

    // ── Naciones y regiones ──────────────────────────────────────────
    { name: "Andor",         alt: [],                    type: "region", px: [1900, 1289] },
    { name: "Cairhien (nación)", alt: [],                type: "region", px: [2577, 1107] },
    { name: "Tear (nación)", alt: [],                    type: "region", px: [2495, 1780] },
    { name: "Illian (nación)", alt: [],                  type: "region", px: [2025, 1878] },
    { name: "Altara",        alt: [],                    type: "region", px: [1677, 1784] },
    { name: "Murandy",       alt: [],                    type: "region", px: [1923, 1477] },
    { name: "Amadicia",      alt: [],                    type: "region", px: [1357, 1709] },
    { name: "Ghealdan",      alt: [],                    type: "region", px: [1445, 1555] },
    { name: "Tarabon",       alt: [],                    type: "region", px: [989, 1477] },
    { name: "Arad Doman",    alt: [],                    type: "region", px: [1050, 916] },
    { name: "Saldaea",       alt: [],                    type: "region", px: [1500, 583] },
    { name: "Kandor",        alt: [],                    type: "region", px: [1977, 505] },
    { name: "Arafel",        alt: [],                    type: "region", px: [2380, 522] },
    { name: "Shienar",       alt: [],                    type: "region", px: [2547, 550] },
    { name: "The Blight",    alt: ["la llaga", "gran llaga"], type: "region", px: [2010, 90] },
    { name: "Aiel Waste",    alt: ["yermo de aiel", "el yermo"], type: "region", px: [2950, 700] },
    { name: "Almoth Plain",  alt: ["llanura de almoth"], type: "region", px: [1009, 1166] },
    { name: "Caralain Grass", alt: ["herbazal de caralain"], type: "region", px: [1848, 1060] },
    { name: "Plains of Maredo", alt: ["llanuras de maredo"], type: "region", px: [2182, 1780] },
    { name: "Hills of Kintara", alt: ["colinas de kintara"], type: "region", px: [2175, 1527] },
    { name: "Rhannon Hills",  alt: ["colinas de rhannon", "rhannon"], type: "region", px: [1640, 1930] },
    { name: "Matherin Manor", alt: ["mansion matherin", "casa matherin", "house matherin", "matherin"], type: "lugar", px: [2280, 1430] },

    // ── Montañas y bosques ───────────────────────────────────────────
    { name: "Mountains of Dhoom", alt: ["montañas de la perdicion", "mountains of doom"], type: "montaña", px: [1984, 311] },
    { name: "Mountains of Mist", alt: ["montañas de la niebla"], type: "montaña", px: [1248, 1452] },
    { name: "Black Hills",   alt: ["colinas negras"],    type: "montaña", px: [1964, 770] },
    { name: "Chishen Mountains", alt: ["montañas chishen", "chishen"], type: "montaña", px: [2085, 1478] },
    { name: "Braem Wood",    alt: ["bosque de braem"],   type: "bosque", px: [2073, 1166] },
    { name: "Haddon Mirk",   alt: [],                    type: "bosque", px: [2502, 1605] },
    { name: "Forest of Shadows", alt: ["bosque de las sombras"], type: "bosque", px: [1385, 1330] },

    // ── Islas ────────────────────────────────────────────────────────
    { name: "Tremalking",    alt: [],                    type: "isla", px: [273, 2018] },
    { name: "Aile Dashar",   alt: [],                    type: "isla", px: [395, 518] },
    { name: "Aile Somera",   alt: [],                    type: "isla", px: [123, 1180] },
    { name: "Aile Jafar",    alt: [],                    type: "isla", px: [505, 1561] },
    { name: "Qaim",          alt: ["quaim"],             type: "isla", px: [1116, 2141] },
    { name: "Cindaking",     alt: [],                    type: "isla", px: [2768, 2107] },

    // ── Mares y costas ───────────────────────────────────────────────
    { name: "Aryth Ocean",   alt: ["oceano aryth", "arith ocean"], type: "mar", px: [470, 873] },
    { name: "Sea of Storms", alt: ["mar de las tormentas"], type: "mar", px: [1950, 2178] },
    { name: "The Dead Sea",  alt: ["mar muerto"],        type: "mar", px: [1064, 175] },
    { name: "Kabal Deep",    alt: ["sima de kabal"],     type: "mar", px: [1784, 1950] },
    { name: "Windbiter's Finger", alt: ["dedo del muerdevientos"], type: "mar", px: [757, 2080] },
    { name: "Fingers of the Dragon", alt: ["dedos del dragon"], type: "mar", px: [2373, 1936] },
    { name: "Bay of Remara", alt: ["bahia de remara"],   type: "mar", px: [2816, 1936] },

    // ── Ríos ─────────────────────────────────────────────────────────
    { name: "River Erinin",  alt: ["rio erinin", "erinin"], type: "río", px: [2332, 1510] }
];
